# Day 4 Exercises
## Object Oriented Programming

#### 1. Create a class called `Book` that has the attributes title, author, pages, price. It also has the method get_price() which returns price, and set_price() to ensure price is numeric.

Then create two instances of this class:

b1:
* title -> 'Practical Programming'
* author -> 'Gries, Campbell, Montojo'
* pages -> 383
* price -> 50

b2:
* title -> 'Building a Career in Data Science'
* author -> 'Robinson, Nolis'
* pages -> 322
* price -> 40

In [1]:
class Book:
    def __init__(self, title, author, pages, price):
        self.title = title
        self.author = author
        self.pages = pages
        self.__price = price

    def get_price(self):
        return self.__price

    def set_price(self, value):
        if not isinstance(value, (int, float)):
            print('Price must be of a numeric value')
        else:
            self.__price = value

b1 = Book('Practical Programming', 'Gries, Campbell, Montojo', 383, 50)
b2 = Book('Building a Career in Data Science', 'Robinson, Nolis', 322, 40)


In [2]:
#this is for testing purposes of the above code block...
b1.set_price(79.99)
b1.get_price()
#This will change the price of b1 to 79.99 and then return it as the changed value.


79.99

In [3]:
b2.set_price('tester')
#this produces a *programmed* error message because the price must be a numeric value.
#everything works!


Price must be of a numeric value


#### 2. Create a `Phone` class that has the attributes model, id, name, brand and price. Create the getters and setters for each attribute. As well as the following methods: calculate_total which takes the price and calculates it by the tax argument.

In [4]:
class Phone:
    def __init__(self, model, ID, name, brand, price):
        self.__model = model
        self.__UserID = ID
        self.__name = name
        self.__brand = brand
        self.__price = price

    def get_model(self):
        return self.__model
    def set_model(self, value):
        if not isinstance(value, str):
            print('Model name input must be text-based')
        else:
            self.__model = value

    def get_UserID(self):
        return self.__UserID
    def set_UserID(self, value):
        if not isinstance(value, str):
            print('UserID input must be text-based')
        else:
            self.__UserID = value

    def get_name(self):
        return self.__name
    def set_name(self, value):
        if not isinstance(value, str):
            print('Name input must be text-based')
        else:
            self.__name = value

    def get_brand(self):
        return self.__brand
    def set_brand(self, value):
        if not isinstance(value, str):
            print('Brand input must be text-based')
        else:
            self.__brand = value

    def get_price(self):
        return self.__price
    def set_price(self, value):
        if not isinstance(value, (int, float)):
            print('Price input must be a numeric value')
        else:
            self.__price = value

    def calculate_total(self, tax_rate):
        return self.__price * (1 + tax_rate)

p1 = Phone('iphone', 'Bob@gmail.com', 'Bob', 'Apple', 1000)
p2 = Phone('Galaxy', 'Mark@outlook.com', 'Mark', 'Samsung', 950)

p1.calculate_total(0.13)


1130.0

## Numpy

In [12]:
import numpy as np

#### 1. Write a code to convert a 1D array to a 2D array with 2 rows.

Original Array: [0 1 2 3 4 5]

Reshaped 2x3 Array:

[[0 1 2]

[3 4 5]]

In [15]:
numbers_array = np.array([0, 1, 2, 3, 4, 5])

numbers_array.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

#### 2. Create a 3×3 NumPy array of all True

*Hint! Use np.ones() with dtype=bool.*

In [32]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### 3. Create a 1D array filled with zeros and another filled with ones

In [42]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [43]:
np.ones(5)

array([1., 1., 1., 1., 1.])

#### 4. Reverse a 1D NumPy array
Ex. arr = np.arange(10)

Output is [9 8 7 6 5 4 3 2 1 0]

*Hint! Use slicing with step = -1.*

In [51]:
arr = np.arange(10)
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 5. Stack these arrays horizontally


a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

In [53]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

#### 6. Perform arithmetic operations on two NumPy arrays element-wise

a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

*   Add two NumPy arrays element by element.
*   Multiply two NumPy arrays element by element.

In [55]:
a + b

array([5, 7, 9])

In [ ]:
a * b

array([ 4, 10, 18])